"""
ML Chat Service Module
----------------------
This module defines the `MLChatService` class, which handles research paper 
retrieval and question answering. It embeds incoming user queries, queries a 
Pinecone vector index for relevant research papers, constructs a structured 
prompt with similarity metrics, and uses Google Gemini to generate dynamic, 
intent-based responses.

Key functionality:
  - Embeds input questions using the recommendation encoding model.
  - Queries Pinecone index `research-papers` namespace for top matching papers.
  - Formats multi-intent prompt guidelines (Paper Recommendation, Concept Explanation, General Research).
  - Integrates Google Gemini API for answer generation with fallback error handling.
  - Formats output reference links targeting arXiv paper abstract IDs.

Exports:
  - ml_chat_service: Singleton instance of `MLChatService` for machine learning chat and retrieval operations.
"""

import os
from typing import Any, Optional
import google.generativeai as genai

from services.ml.models.recommendation.recommendation import (
    model,
    index,
)


class MLChatService:
    """
    Service responsible for handling research paper querying, context 
    construction, and integrating with Gemini LLM for AI assistant responses.
    """

    def chat(
        self,
        question: str,
        provider: Optional[str] = None,
        api_key: Optional[str] = None,
    ) -> dict[str, Any]:
        """
        Processes a user question, retrieves top relevant papers from Pinecone, 
        and generates an intent-driven answer via Google Gemini.

        Args:
            question (str): The search query or question submitted by the user.
            provider (Optional[str]): Optional LLM provider identifier.
            api_key (Optional[str]): Optional explicit API key for Google Gemini.

        Returns:
            dict[str, Any]: A dictionary containing:
                - "answer" (str): The response generated by Gemini (or fallback).
                - "references" (list[dict]): A list of dicts containing paper titles and arXiv URLs.
        """

        # ---------------------------------------------
        # 1. Embed question
        # ---------------------------------------------
        query_embedding = model.encode(
            [question],
            convert_to_numpy=True
        )

        # ---------------------------------------------
        # 2. Retrieve papers from Pinecone
        # ---------------------------------------------
        results = index.query(
            vector=query_embedding.tolist()[0],
            top_k=3,
            namespace="research-papers",
            include_metadata=True,
        )

        papers = []
        for match in results.get("matches", []):
            metadata = match.get("metadata", {})

            papers.append({
                "id": match.get("id", ""),
                "title": metadata.get("title", ""),
                "authors": metadata.get("authors", ""),
                "category": metadata.get("category", ""),
                "update_date": metadata.get("update_date", ""),
                "similarity": round(
                    match.get("score", 0) * 100,
                    2
                ),
            })

        # ---------------------------------------------
        # 3. Build research context (Includes Similarity Score)
        # ---------------------------------------------
        context = "\n\n".join(
            f"""
Paper:{paper["title"]}

Authors:{paper["authors"]}

Category:{paper["category"]}

Publication Date:{paper["update_date"]}

Similarity:{paper["similarity"]}%
"""
            for paper in papers
        )

        # ---------------------------------------------
        # 4. Configure Gemini API Key
        # ---------------------------------------------
        if api_key:
            genai.configure(api_key=api_key)
        else:
            genai.configure(
                api_key=os.getenv("GEMINI_API_KEY")
            )

        # ---------------------------------------------
        # 5. Build Intent-Based Prompt
        # ---------------------------------------------
        prompt = f"""
You are an AI research assistant for a research-paper
discovery and question-answering system.

Your response style MUST depend on the user's question.

========================================================
TYPE 1: RESEARCH PAPER / RECOMMENDATION QUESTION
========================================================

Use this format when the user asks for:
- research papers
- paper recommendations
- papers to read
- papers related to a topic
- literature related to a topic
- relevant research
- recommended publications
- papers on a specific subject

Examples:
"Give me papers on machine learning"
"Recommend research papers about NLP"
"Show me papers related to cloud computing"
"What papers should I read about computer vision?"

For these questions, DO NOT write a long essay.

Return the retrieved papers in this format:

## Recommended Research Papers

### 1. <Paper Title>

**Authors:** <Authors>
**Category:** <Category>
**Publication Date:** <Date>
**Similarity:** <Similarity if available>

**Why it is relevant:**  
Write 1-3 concise sentences explaining why this
paper is relevant to the user's question.

### 2. <Paper Title>

**Authors:** <Authors>
**Category:** <Category>
**Publication Date:** <Date>
**Similarity:** <Similarity if available>

**Why it is relevant:**  
Write 1-3 concise sentences.

Continue for all retrieved papers.

At the end, optionally provide:

### Summary

- <main research area>
- <main research area>
- <main research area>

IMPORTANT:
- Use the retrieved papers as the source of paper metadata.
- Do not invent authors, dates, categories, titles or results.
- Do not create papers that are not in the retrieved context.
- Do not turn the response into a long narrative.
- Keep recommendation responses structured and easy to scan.

========================================================
TYPE 2: NORMAL KNOWLEDGE / CONCEPT QUESTION
========================================================

If the user asks a normal conceptual or educational question,
such as:

"What is machine learning?"
"What is deep learning?"
"Explain overfitting"
"What is a neural network?"
"What is supervised learning?"

DO NOT list the retrieved papers as the main answer.

Instead:

1. Give a short direct explanation in 1-2 paragraphs.
2. Add bullet points when useful.
3. Use simple and technically accurate language.
4. Give an example when it improves understanding.
5. Keep the response concise unless the user asks for detail.

Example structure:

## What is Machine Learning?

<short explanation>

### Key Points

- Point 1
- Point 2
- Point 3

### Example

<short example>

If the retrieved papers are directly relevant, you may
briefly mention them at the end under:

### Related Research

- <Paper title>
- <Paper title>

Do NOT force papers into the answer when they are not
relevant.

========================================================
TYPE 3: GENERAL RESEARCH QUESTION
========================================================

For questions such as:

"What are the latest approaches to machine learning?"
"How is machine learning used in healthcare?"
"What are the challenges in NLP?"

Give a normal explanatory answer first.

Then, if the retrieved papers are relevant, add:

### Relevant Research

1. **<Paper Title>** — <one sentence explaining relevance>
2. **<Paper Title>** — <one sentence explaining relevance>

========================================================
GENERAL RULES
========================================================

- Always answer the user's actual question first.
- Use retrieved papers when they are relevant.
- Do not mention "retrieved research" unnecessarily.
- Do not invent information.
- Do not invent experimental results, statistics or claims.
- Do not repeat the same information.
- Prefer concise, readable Markdown.
- Use headings and bullet points where appropriate.
- For paper recommendations, ALWAYS use the structured
  paper format above.
- For normal questions, ALWAYS prioritize the explanation
  over the paper list.

User question:{question}

Retrieved research papers:{context}
"""

        # ---------------------------------------------
        # 6. Generate Response via Gemini
        # ---------------------------------------------
        gemini = genai.GenerativeModel(
            "gemini-3-flash-preview"
        )

        try:
            response = gemini.generate_content(prompt)
            answer = response.text
        except Exception as e:
            print(f"Gemini generation failed: {e}")

            if papers:
                paper_names = "\n".join(
                    f"- {paper['title']}"
                    for paper in papers
                )

                answer = (
                    "Based on the research papers retrieved from "
                    "the ResearchAI knowledge base, the question "
                    "is related to the following research areas:\n\n"
                    f"{paper_names}\n\n"
                    "These papers provide relevant research context "
                    "for understanding the topic. The retrieved "
                    "papers can be explored below for more detailed "
                    "information."
                )
            else:
                answer = (
                    "I could not find relevant research information "
                    "for this question in the knowledge base."
                )

        # ---------------------------------------------
        # 7. Construct References Payload
        # ---------------------------------------------
        references = [
            {
                "title": paper["title"],
                "paper_url": (
                    f"https://arxiv.org/abs/{paper['id']}"
                ),
            }
            for paper in papers
        ]

        return {
            "answer": answer,
            "references": references,
        }


# Global singleton instance
ml_chat_service = MLChatService()