"""
FILE CONTENTS & OVERVIEW:
-------------------------
This file defines the `ChatState` type schema using Python's `TypedDict`.
It represents the shared state object passed between execution nodes in the LangGraph chat processing workflow.

Key attributes:
  - db: Active SQLAlchemy database session.
  - session_id: String representation of the session identifier.
  - session_uuid: Native object/UUID representation of the chat session primary key.
  - provider: Name of the LLM provider service (e.g., "openai", "anthropic", "groq").
  - api_key: Optional API credentials key string for authentication.
  - question: Incoming user query string.
  - history: Formatted string transcript of previous conversation messages.
  - context: Combined text content retrieved from vector database matches.
  - answer: Final response generated by the LLM provider.
  - references: List of metadata dictionaries mapping retrieved chunks back to their source files and pages.
"""

from typing import TypedDict
from sqlalchemy.orm import Session


class ChatState(TypedDict):
    """
    Typed dictionary defining the state payload passed along nodes in the LangGraph execution graph.

    Attributes:
        db (Session): Active SQLAlchemy database session instance.
        session_id (str): Chat session identifier string.
        session_uuid (object): UUID object corresponding to the database primary key.
        provider (str): Identifier for the requested AI provider service.
        api_key (str | None): Optional API key string used to authenticate with AI provider APIs.
        question (str): Current input question submitted by the user.
        history (str): String representation of formatted previous message history.
        context (str): Concatenated text content of retrieved background documents.
        answer (str): Text response generated by the LLM model.
        references (list[dict]): Structured metadata references for retrieved context documents (e.g., text, source file, page).
    """

    db: Session

    session_id: str

    session_uuid: object

    provider: str

    api_key: str | None

    question: str

    history: str

    context: str

    answer: str

    references: list[dict]