"""
FILE CONTENTS & OVERVIEW:
-------------------------
This file defines the `AIChatService` class, which orchestrates non-streaming (and commented streaming) chat logic.
It processes user incoming questions by validating session UUIDs, assembling input state, and executing the compiled LangGraph execution graph (`chat_graph`).

Key functionality:
  - chat(): Validates `session_id` into a valid `UUID`, invokes `chat_graph` with the initial state, and returns generated answers alongside retrieved reference citations.
  - stream(): (Commented out) Prototype generator method demonstrating real-time token streaming using LLM provider stream mechanisms.

Exports:
  - ai_chat_service: Singleton instance of `AIChatService` for application-wide AI chat operations.
"""

from typing import Any, Generator
from uuid import UUID

from app.core.ai_manager import ai_manager
from app.core.exceptions import AppException
from app.core.logger import logger
from app.repositories.message_repository import message_repository
from services.ai.graph import chat_graph
from services.ai.graph.prompts import SYSTEM_PROMPT
from services.ai.retriever import retriever


class AIChatService:
    """
    Service class orchestrating AI chat execution using LangGraph workflows and custom LLM providers.
    """

    def chat(
        self,
        db: Any,
        message: str,
        session_id: str,
        provider: str = "gemini",
        api_key: str = None,
    ) -> dict[str, Any]:
        """
        Executes a synchronous chat request through the LangGraph workflow graph.

        Args:
            db (Session): Active SQLAlchemy database session.
            message (str): Incoming question/message string from the user.
            session_id (str): UUID string identifier of the target chat session.
            provider (str, optional): AI provider identifier (e.g., 'gemini', 'openai'). Defaults to "gemini".
            api_key (str, optional): Custom API key string for provider access. Defaults to None.

        Returns:
            dict[str, Any]: Dictionary containing the final generated 'answer' string and retrieved 'references' metadata list.

        Raises:
            AppException: If session_id is missing (400) or has an invalid UUID format (400).
        """
        if not session_id:
            raise AppException(
                "Session ID is required.",
                400,
            )

        try:
            session_uuid = UUID(session_id)
        except ValueError:
            raise AppException(
                "Invalid Session ID format.",
                400,
            )

        logger.info(f"Question received for {session_id}")

        state = {
            "db": db,
            "session_id": session_id,
            "session_uuid": session_uuid,
            "provider": provider or "gemini",
            "api_key": api_key,
            "question": message,
        }

        result = chat_graph.invoke(state)

        logger.success("Answer generated successfully")

        return {
            "answer": result["answer"],
            "references": result["references"],
        }

#     def stream(
#         self,
#         db: Any,
#         message: str,
#         session_id: str,
#         provider: str = "gemini",
#         api_key: str = None,
#     ) -> Generator[str, None, None]:
#         """
#         Executes a streaming chat request using real-time LLM token generation.
#
#         Args:
#             db (Session): Active SQLAlchemy database session.
#             message (str): Incoming question string from the user.
#             session_id (str): UUID string identifier of the target chat session.
#             provider (str, optional): AI provider identifier. Defaults to "gemini".
#             api_key (str, optional): Custom API key string for provider access. Defaults to None.
#
#         Yields:
#             str: Incremental output text chunks generated by the LLM.
#
#         Raises:
#             AppException: If session_id is missing or invalid.
#         """
#         if not session_id:
#             raise AppException(
#                 "Session ID is required.",
#                 400,
#             )
#
#         try:
#             session_uuid = UUID(session_id)
#         except ValueError:
#             raise AppException(
#                 "Invalid Session ID format.",
#                 400,
#             )
#
#         history = message_repository.get_history(
#             db=db,
#             session_id=session_uuid,
#         )
#
#         conversation = ""
#         for msg in history:
#             conversation += f"{msg.role}: {msg.content}\n"
#
#         result = retriever.retrieve(
#             session_id=session_id,
#             question=message,
#         )
#
#         context = "\n\n".join(result["documents"][0]) if result.get("documents") else ""
#
#         prompt = f"""
# Conversation
#
# {conversation}
#
# Context
#
# {context}
#
# Question
#
# {message}
# """
#
#         llm = ai_manager.get_provider(
#             provider,
#             api_key,
#         )
#
#         answer = ""
#
#         for chunk in llm.stream_generate(
#             prompt,
#             SYSTEM_PROMPT,
#         ):
#             answer += chunk
#             yield chunk
#
#         message_repository.create(
#             db=db,
#             session_id=session_uuid,
#             role="user",
#             content=message,
#         )
#
#         message_repository.create(
#             db=db,
#             session_id=session_uuid,
#             role="assistant",
#             content=answer,
#         )


# Global singleton instance of AIChatService
ai_chat_service = AIChatService()