"""
FILE CONTENTS & OVERVIEW:
-------------------------
This file defines the Pydantic data validation schemas for the AI module.
It structures request and response payloads across four primary functional areas:
  1. Chat schemas: Payloads for AI chat queries, source citations/references, and chat responses.
  2. Summary schemas: Inputs and outputs for document or chat session summarization.
  3. Upload schemas: Response structure returning session and page information for uploaded documents.
  4. Session management schemas: Request schema for renaming chat sessions.
"""

from pydantic import BaseModel


# ---------- Chat ----------

class AIChatRequest(BaseModel):
    """
    Schema for incoming AI chat request payloads.

    Attributes:
        message (str): The user's input prompt or question.
        session_id (str | None): Optional existing chat session identifier. Defaults to None.
        provider (str | None): Optional target AI model provider (e.g., 'gemini'). Defaults to None.
        api_key (str | None): Optional custom API key for the LLM service. Defaults to None.
    """
    message: str
    session_id: str | None = None
    provider: str | None = None
    api_key: str | None = None


class AIReference(BaseModel):
    """
    Schema representing a reference or source citation used in an AI response.

    Attributes:
        text (str): Excerpt or quote from the reference source.
        source (str): Name or path of the source document/file.
        page (int): Page number in the source document where the reference is located.
    """
    text: str
    source: str
    page: int


class AIChatResponse(BaseModel):
    """
    Schema for outbound AI chat response payloads.

    Attributes:
        answer (str): The primary answer text generated by the AI.
        references (list[AIReference]): List of cited source references supporting the answer.
    """
    answer: str
    references: list[AIReference]


# ---------- Summary ----------

class SummaryRequest(BaseModel):
    """
    Schema for requesting document or session summaries.

    Attributes:
        session_id (str): Unique identifier of the session to summarize.
        mode (str): Granularity or style of summary (e.g., 'short', 'detailed'). Defaults to "short".
    """
    session_id: str
    mode: str = "short"


class SummaryResponse(BaseModel):
    """
    Schema for returning generated summary outputs.

    Attributes:
        summary (str): Narrative text summarizing the session/document content.
        bullet_points (list[str]): Key takeaways structured as bullet points.
    """
    summary: str
    bullet_points: list[str]


# ---------- Upload ----------

class UploadResponse(BaseModel):
    """
    Schema for responses returned after successful file upload processing.

    Attributes:
        session_id (str): Generated session identifier associated with the uploaded file.
        filename (str): Name of the processed upload file.
        total_pages (int): Total number of pages extracted from the uploaded document.
    """
    session_id: str
    filename: str
    total_pages: int


class RenameChat(BaseModel):
    """
    Schema for requests updating the title of a chat session.

    Attributes:
        title (str): New title name to set for the specified chat session.
    """
    title: str